export const PRODUCTS_PLANT_DATA = [
	{
		id: 1,
		img: '../plant/calathea-plant.png',
		category: 'Trendy House Plant',
		name: 'Calathea plant',
		price: 198,
	},
	{
		id: 2,
		img: '../plant/desk-plant.png',
		category: 'Trendy House Plant',
		name: 'Desk plant',
		price: 269,
	},
	{
		id: 3,
		img: '../plant/calathea-ai-plant.png',
		category: 'Trendy House Plant',
		name: 'Calathea ai plant',
		price: 178,
	},
	{
		id: 4,
		img: '../plant/cal-874-plant.png',
		category: 'Trendy House Plant',
		name: 'Cal 874 plant',
		price: 78,
	},
	{
		id: 5,
		img: '../plant/show-plant.png',
		category: 'Trendy House Plant',
		name: 'Show plant',
		price: 128,
	},
	{
		id: 6,
		img: '../plant/calat-02-plant.png',
		category: 'Trendy House Plant',
		name: 'Calat 02 plant',
		price: 278,
	},
	{
		id: 7,
		img: '../plant/jade-plant.png',
		category: 'Trendy House Plant',
		name: 'Jade plant',
		price: 128,
	},
	{
		id: 8,
		img: '../plant/baby-rubberplant.png',
		category: 'Trendy House Plant',
		name: 'Baby Rubberplant',
		price: 78,
	},
	{
		id: 9,
		img: '../plant/golden-pothos.png',
		category: 'Trendy House Plant',
		name: 'Golden Pothos',
		price: 118,
	},
	{
		id: 10,
		img: '../plant/chocolate-mint.png',
		category: 'Trendy House Plant',
		name: 'Chocolate Mint',
		price: 58,
	},
	{
		id: 11,
		img: '../plant/split-leaf-philodendron.png',
		category: 'Trendy House Plant',
		name: 'Split Leaf Philodendron',
		price: 58,
	},
	{
		id: 12,
		img: '../plant/swiss-cheese-plant.png',
		category: 'Trendy House Plant',
		name: 'Swiss Cheese Plant',
		price: 158,
	},
];

export const POTS_ACCESSORIES_DATA = [
	{
		id: 1,
		img: '../potsAccessories/eyes-pot-photoroom.png',
		category: 'Pots',
		name: 'Eyes Pot',
		price: 195,
	},
	{
		id: 2,
		img: '../potsAccessories/stone-footed-planter-photoroom.png',
		category: 'Pots',
		name: 'Stone Footed Planter',
		price: 195,
	},
	{
		id: 3,
		img: '../potsAccessories/gradient-cyclinder-pots-photoroom.png',
		category: 'Pots',
		name: 'Gradient Cyclinder Pots',
		price: 149,
	},
	{
		id: 4,
		img: '../potsAccessories/apron-photoroom.png',
		category: 'Accessories',
		name: 'Gardening Apron',
		price: 67,
	},
	{
		id: 5,
		img: '../potsAccessories/indoor-potting-soil-photoroom.png',
		category: 'Accessories',
		name: 'Indoor Potting Soil - 500g',
		price: 67,
	},
	{
		id: 6,
		img: '../potsAccessories/spray-photoroom.png',
		category: 'Accessories',
		name: 'Fine Continuous Plant Sprayer - 300ml',
		price: 64,
	},
	{
		id: 7,
		img: '../potsAccessories/book-house-plant-photoroom.png',
		category: 'Accessories',
		name: 'Book - My Houseplant Changed My Life',
		price: 93,
	},
	{
		id: 8,
		img: '../potsAccessories/book-succulents-photoroom.png',
		category: 'Accessories',
		name: 'Book - Succulents Simplified',
		price: 93,
	},
	{
		id: 9,
		img: '../potsAccessories/book-leaf-photoroom.png',
		category: 'Accessories',
		name: 'Book - Leaf Supply',
		price: 93,
	},
	{
		id: 10,
		img: '../potsAccessories/light-up-terrarium-photoroom.png',
		category: 'Accessories',
		name: 'Light Up Terrarium',
		price: 106,
	},
];
